public with sharing class VariablesandKeyWords {
    // All the objects in salesforce can use as datatypes in salesforce.
    // Apart from that,

    // The variable which exists in class are called class variables.

    public Integer i = 10;
    private Boolean checkIfRecordExits = false;
    Date todaysDate;
    Datetime currentTime;
    String myName = 'Vishnu';
    Account accRecord = null;
    Contact conRecord;
    List<String> myAcceptedValues;
    Set<Id> myIds;
    Id accountId;
}